### ISSUE TITLE
Change how clicking apps work

### ISSUE THREAD

**Issue by chadalen** [linuxappstore/linuxappstore-frontend#12]
Currently when clicking an app depending on the type..
- AppImage will bring you to the GitHub releases page
- Flatpak will download a reference file (used by the gnome plugin. I believe this only works with gnome based desktop environments)
- Snap will download a local snap

For right now, what I'm going to do is change these so
- AppImage will open a url to the app at appimagehub
- Flatpak will open a url to the app at flathub
- Snap will open url to the app at snapcraft

This will be temporary. Eventually this will be replaced with a details view #10

**Comment by probonopd** [comment]
Note that not for all AppImages we have a direct download link. In this case, you could link e.g., to the https://appimage.github.io/SonicVisualiser/ (just as an example). We hope to add more download links in the future.

**Comment by chadalen** [comment]
@probonopd Thanks for the info. Yeah I think I'll do that for now. Quick question for you though. What happens if 2 people create an AppImage with the same name? How would it be displayed on appimage.github.io?

**Comment by probonopd** [comment]
The one from the official author would "win". We are over 800 apps now and never have had such a situation though.

**Comment by chadalen** [comment]
@probonopd Ok, so another question I have is. Can I get a new property e.g "id" to the feed [here](https://appimage.github.io/feed.json) for each app that will uniquely identify them? Can be a GUID or auto incremented id. Basically like a primary key in a relational db. If a user can request changing the name of their app. Then I would need a way to determine if the app they changed is still the same app or else I'll get duplicates in my database. Snaps use a GUID "snap_id" [See here](https://search.apps.ubuntu.com/api/v1/search), flatpaks [See here](https://flathub.org/api/v1/apps/) use a package name. "flatpakAppId".

**Comment by probonopd** [comment]
We use the names of the files in https://github.com/AppImage/appimage.github.io/tree/master/data as our identifiers; if an application is renamed then it will not appear in the feed under the old identifier anymore.
