### ISSUE TITLE
AppImage feed

### ISSUE THREAD

**Issue by probonopd** [linuxappstore/linuxappstore-frontend#2]
Are you aware of the feed at https://appimage.github.io/feed.json? Should hopefully make it easy to populate linux-app-store.

**Comment by chadalen** [comment]
@probonopd No I was not, thanks for this! I was working on a web scraper using
[https://appimage.github.io/search.json](https://appimage.github.io/search.json)

**Comment by chadalen** [comment]
See https://linuxappstore.io/

**Comment by probonopd** [comment]
Thank you.
