### ISSUE TITLE
Some AppImages are missing?

### ISSUE THREAD

**Issue by probonopd** [linuxappstore/linuxappstore-frontend#22]
On https://appimage.github.io/ we claim to have 856 apps, yet https://linuxappstore.io/ says there are 630. Are you filtering some out or is our json feed somehow not delivering all?

**Comment by chadalen** [comment]
I do skip some that have missing fields.

You can look at this script and see what I skip.
[https://github.com/linuxappstore/linuxappstore-updater/blob/master/appimageupdater.py](https://github.com/linuxappstore/linuxappstore-updater/blob/master/appimageupdater.py)

If the name doesn't exist.
If there's no direct download (This is probably the issue see [here](https://github.com/linuxappstore/linuxappstore-updater/blob/master/appimageupdater.py#L132))

**Comment by probonopd** [comment]
> If there's no direct download (This is probably the issue see here)

Then please link to the corresponding appimage.github.io/<AppName> page. Not all AppImages can have direct download links for technical reasons: We simply don't know the direct link to the latest version.

**Comment by joseluissdb** [comment]
Falta kdenlive

**Comment by chadalen** [comment]
> On https://appimage.github.io/ we claim to have 856 apps

[https://appimage.github.io/feed.json](https://appimage.github.io/feed.json)

Feed.json above only has 786 apps listed. Fixing the issue above I was able to get all 786 apps.

**Comment by probonopd** [comment]
> Looks like search.json has some bad data in it. e.g has...
feed.json, robots.txt, sitemap.xm, appstream.xml, search.json, script.js

Indeed that is a bug, thanks for investigating. Do you know what is wrong with the others?

**Comment by probonopd** [comment]
Err, `search.json` is not for public consumption (it was a test for making a search on github.appimage.io but that is not working anyway).

Only `feed.json` is what you should be using. Let me know if it is missing something that you need.

**Comment by chadalen** [comment]
> Do you know what is wrong with the others?
I don't. I'm going to close this issue since all the apps in feed.json will display now. This will be in the 0.3.2 release.
