### ISSUE TITLE
Links didn't work

### ISSUE THREAD

**Issue by gruessung** [linuxappstore/linuxappstore-frontend#24]
On your index page no link on any app is working.
Browser: Firefox ESR 60.6.1esr
Hotfix: Change button-Tag to a div-Tag

![apps](https://user-images.githubusercontent.com/433331/57208675-61245900-6fd5-11e9-9110-be8817c8cb10.PNG)

**Comment by N0rbert** [comment]
Same with Firefox ESR 52.9.0 and SeaMonkey 2.49.4.

**Comment by chadalen** [comment]
I believe this is only an issue with ESR Firefox. SeaMonkey is based on an old Firefox version so it would have this problem too. On newer Firefox versions this has been fixed. This seems to be an issue with the CardActionArea in React Material that uses a button underneath. I'll see if I can swap that component out and see if that fixes the issue.

**Comment by probonopd** [comment]
It would be good if linuxappstore would work with older browsers, too. Not everyone has root rights on the machine and can "just" install a newer browser. Think corporations, universities, etc.

**Comment by chadalen** [comment]
This is fixed in commit c674e9c4da2e520d14b940ee272b273ad3ef3ac1 will be in release 0.3.2
