### ISSUE TITLE
Show a message when there is no match when searching

### ISSUE THREAD

**Issue by adamsts** [linuxappstore/linuxappstore-frontend#28]
Hello. Great idea for a project. One thing that I noticed was when I searched for something that isn't in any of the stores there is no indication that it wasn't found. I am just shown other apps that don't seem to be related. My suggestion, if possible, would be to show a simple message that a match wasn't found. I don't mind the other results being shown as well but it would make it less confusing to know that there wasn't an exact match. Thanks for considering my idea.

**Comment by chadalen** [comment]
I'm going to put this in release 0.3.2 since this is a bug. The "Recently Updated" gets moved up and looks like its apart of your search result. Thanks for letting me know.
