### ISSUE TITLE
Search should be improved

### ISSUE THREAD

**Issue by N0rbert** [linuxappstore/linuxappstore-frontend#29]
Steps to reproduce:
1. Open 
2. Try to search for `markdown` or `Markdown`

Expected results:
* search results contain well known _VNote_, _Marker_, _Mark Text_, _CureMarkEd_ and may be other editors

Actual results:
* search results contain only three editors:

![markdown-3-editors](https://user-images.githubusercontent.com/309456/57569889-641faf00-7404-11e9-9972-c933283abb93.png)

**Comment by probonopd** [comment]
AppImage `feed.json` currently has 8 `markdown`-related AppImages.

**Comment by chadalen** [comment]
Currently I only search by title so that's why you don't see those showing up in your search result. Adding searching by description as well will solve this problem. I'll have to see how large the description is for these 3 different formats so hopefully it won't affect performance.

**Comment by chadalen** [comment]
Added in commit 53d82a65cbf16fac9949d136f2d3632cd718ac35 will be in 0.4.0 release
