### ISSUE TITLE
Search field does not react on <Enter> key

### ISSUE THREAD

**Issue by N0rbert** [linuxappstore/linuxappstore-frontend#30]
Steps to reproduce:
1. Open store
2. Start typing search term
3. See that page is loaded, but search was not performed
4. Hit `<Enter>` to perform search

Expected results:
*  search field reacts on `<Enter>` key, search is performed

Actual results:
* search field does not react on `<Enter>` key, search is not performed

**Comment by chadalen** [comment]
@N0rbert Can you give me an example of what you typed in in the search box?

You shouldn't have to use the enter key. It's suppose to perform a search as you type.

**Comment by N0rbert** [comment]
It is side-effect of modern AJAX (or what is used on this page instead of user-driven *submit* action).
I searched for *vlc* when page was not completely loaded:

![vlc](https://user-images.githubusercontent.com/309456/57734275-38255780-76aa-11e9-960c-030e805fd572.gif)

I tested this on clean firefox profile without addons.

**Comment by chadalen** [comment]
@N0rbert 
Try searching before the page has been loaded now.
