### ISSUE TITLE
Convert site over to Gatsby

### ISSUE THREAD

**Issue by chadalen** [linuxappstore/linuxappstore-frontend#43]
**[Gatsby](https://www.gatsbyjs.org/)** will have the following benefits

- Allow people to contribute easier (e.g no programming experience required, can add a new json, or md file to submit a new app)

- No server

- No database

- Easier setup

- Significantly faster

- Free hosting (would use [https://www.netlify.com/](https://www.netlify.com/)

This would only be for the web app version. Desktop version using electron would use the API's from various sources.

The big disadvantage towards this is that we wouldn't be able to create a login system since we don't have a back end however I think this is a good thing because of user privacy.

**Comment by chadalen** [comment]
Decided not to do this because we wouldn't be able to have features such as popular apps, star ratings, statistics, login and write reviews on apps. Once the project is a bit further I'll look into getting a sponsor to cover production costs.

**Comment by probonopd** [comment]
Have you considered using something like to build a DApp ("Decentralized Application", think peer-to-peer website)? E.g., https://blog.qtum.org/how-to-build-a-dapp-based-on-qtum-and-ipfs-692bc3ab607a

**Comment by chadalen** [comment]
@probonopd No I have not. I don't think it's a big deal for a centralized vps. I just need to find a cheaper vps. I would like to create a login system where users can submit a change to an app where a user with privileges can approve the change. (similar to how GitHub pull requests work) if did this it would help make contributing easier. If I plan to have a login system I don't think a decentralized app is a good idea.
